#!/usr/bin/env bash

cd ~/.xmonad

set -e

function buildProject() {
  # stack --stack-yaml stack.yml clean
  touch xmonad.hs # force rebuild configs in compileConfig
  rm -f xmonad.hi xmonad.o
  stack --stack-yaml stack.yml -j8 install xmobar --flag xmobar:with_threaded --flag xmobar:with_utf8 --flag xmobar:with_xft --flag xmobar:with_alsa --flag xmobar:with_xpm --ghc-options="-threaded -dynamic --with-rtsopts=-V0"
  stack --stack-yaml stack.yml -j8 build --ghc-options="-threaded -dynamic -j8"
}

function compileConfig() {
  if test "$1" -nt ./xmonad.hs ; then
    echo "Compilation skipped as $1 is newer than the source"
  else
    stack --stack-yaml stack.yml ghc -- -j8 --make xmonad.hs -threaded -dynamic -i -ilib -fno-force-recomp -main-is main -v -o $1
  fi
}

if test "$1" = "--rebuild" ; then
  buildProject
  shift
fi

compileConfig "$1" || (buildProject && compileConfig)


# pkgdb="$(stack --nix --stack-yaml stack.yml path | grep 'local-pkg-db:' | awk '{print $2}')"
# stack --stack-yaml stack.yml ghc -- --make xmonad.hs -threaded -dynamic -i -ilib -package 'process-1.6.3.0' -fforce-recomp  -main-is main -v -o $1

