#!/usr/bin/env bash

cd ~/.xmonad

set -e

function buildProject() {
  # stack --stack-yaml stack.yml clean
  rm -f xmonad.hi xmonad.o
  stack --stack-yaml stack.yml -j8 install xmobar --flag xmobar:all_extensions --ghc-options="-threaded -dynamic -j8 --with-rtsopts=-V0"
  stack --stack-yaml stack.yml -j8 build --ghc-options="-threaded -dynamic -j8"
}

function compileConfig() {
  stack --stack-yaml stack.yml ghc -- -j8 --make xmonad.hs -threaded -dynamic -i -ilib -fforce-recomp  -main-is main -v -o $1
}

if test "$1" = "--rebuild" ; then
  buildProject
  shift
fi
compileConfig "$1" || (buildProject && compileConfig)


# pkgdb="$(stack --nix --stack-yaml stack.yml path | grep 'local-pkg-db:' | awk '{print $2}')"
# stack --stack-yaml stack.yml ghc -- --make xmonad.hs -threaded -dynamic -i -ilib -package 'process-1.6.3.0' -fforce-recomp  -main-is main -v -o $1

