resolver: lts-18.19
nix:
  enable: true
  packages: [
     nix
     gcc
     x11
     xorg.libX11
     xorg.libXext
     xorg.libXinerama
     xorg.libXrandr
     xorg.libXrender
     xorg.libXScrnSaver
     xorg.libXft
     libffi
     pkgconfig
     gmp
     wirelesstools
     alsaLib
     zlib
     xorg.libXpm
     ]  
flags:
  xmonad-contrib:
    pedantic: false
    use_xft: true
  xmonad:
    pedantic: false
packages:
- xmonad/
- xmonad-contrib/
extra-deps:
- unix-2.7.2.2
- process-1.6.9.0
- iwlib-0.1.0
- X11-1.10@sha256:ed01fba28081d6922462c2727a9a2e71f8ec3d962ed18963eee0c770558817d9,3703
  # - libmpd-0.9.0.10@sha256:5a2ff5795085425db11e76332833f2596c5512c861c41272489ed29b725e5538,4011

