resolver: lts-12.4
nix:
  enable: true
  packages:
  - gcc
  - x11
  - xorg.libX11
  - xorg.libXext
  - xorg.libXinerama
  - xorg.libXrandr
  - xorg.libXrender
  - xorg.libXScrnSaver
  - xorg.libXft
flags:
  xmonad-contrib:
    testing: false
    use_xft: false
  xmonad:
    testing: false
packages:
- xmonad/
- xmonad-contrib/
extra-deps:
- unix-2.7.2.2
- process-1.6.4.0
