#!/bin/bash

xsetroot -cursor_name left_ptr
setxkbmap gb
# xmodmap  ~/.Xmodmap
# xcompmgr -cfF -t-9 -l-11 -r9 -o.95 -D6 &
compton -b
xset s 300 240
xss-lock -n ~/.xmonad/bin/dim_screen.sh -- slock &
feh --bg-tile ~/.xmonad/wallpaper.jpg
pulseaudio --start &
# xflux -l 51.5 -g -0.12 -k 4200
# amixer cset "numid=14,iface=MIXER,name='Master Playback Volume'" on
