#!/usr/bin/env bash

DOTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
LN="ln --backup=numbered -nvTfs"

function install() {
  from="$DOTDIR/$1"
  to="$2"

  test -e "$from" || { echo "Could not find source files to install from $from" 1>&2 ; return 1; }

  CMD="$LN '$from' '$to'"
  if test \( -w "$to" -o ! -e "$to" \) -a -w "$(dirname "$to")" ; then
    sh -c "$CMD"
  else
    echo "Installing $from to $to needs root permissions, will use sudo now."
    sudo sh -c "$CMD"
  fi
}


set +x
set -e

cd "$HOME"
# yadm submodule add --depth 1 -f https://github.com/ryanoasis/nerd-fonts.git .local/share/fonts/nerd-fonts
yadm submodule update --progress --recommend-shallow --init --recursive -f

NERD_FONTS_TARGET="$HOME/.local/share/fonts/nerd-fonts"

if ! test -d "$NERD_FONTS_TARGET" ; then
  rm -rf "$NERD_FONTS_TARGET".tmp
  mkdir -p "$NERD_FONTS_TARGET".tmp
  pushd "$NERD_FONTS_TARGET".tmp/..
  test -f nerd-fonts.zip || curl -L4 'https://github.com/ryanoasis/nerd-fonts/archive/master.zip' -o nerd-fonts.zip
  unzip -q nerd-fonts.zip -d "$NERD_FONTS_TARGET".tmp/
  mv "$NERD_FONTS_TARGET".tmp/nerd-fonts-master/patched-fonts "$NERD_FONTS_TARGET"
  rm -rf "$NERD_FONTS_TARGET".tmp
  fc-cache -f
  popd
fi

pushd "$NERD_FONTS_TARGET"/..
test -d FontAwesome || (
  test -f font-awesome.zip || curl -L4 'https://github.com/FortAwesome/Font-Awesome/archive/5.8.1.zip' -o font-awesome.zip
  unzip -j font-awesome.zip "Font-Awesome-5.8.1/otfs/*.otf" -d ./FontAwesome
  fc-cache -f
)
popd

test -d /etc/nixos && install nixos/configuration.nix /etc/nixos/configuration.nix

